--EXERCICIO USANDO CASE
SELECT 
	NOME,
	(CASE
	WHEN LIMITE_DE_CREDITO >= 150000 THEN 'CLIENTE GRANDE'
	WHEN LIMITE_DE_CREDITO > 115000 AND LIMITE_DE_CREDITO < 110000 THEN 'CLIENTE MEDIO'
	ELSE 'CLIENTE PEQUENO'
	END) AS CLASSIFICACAO
FROM TABELA_DE_CLIENTES
ORDER BY CLASSIFICACAO;
