--EXERCICIO PARA JUNTAR AS TABELAS UTILIZANDO INNER JOIN
SELECT 
	ITENS.CODIGO_DO_PRODUTO, 
	PROD.NOME_DO_PRODUTO,
	SUM(QUANTIDADE) AS QUANTIDADE 
FROM 
	ITENS_NOTAS_FISCAIS AS ITENS
INNER JOIN TABELA_DE_PRODUTOS AS PROD
	ON PROD.CODIGO_DO_PRODUTO = ITENS.CODIGO_DO_PRODUTO
GROUP BY 
	ITENS.CODIGO_DO_PRODUTO,
	PROD.NOME_DO_PRODUTO
HAVING SUM(QUANTIDADE) > 394000 
ORDER BY SUM(QUANTIDADE) DESC;
