CREATE TABLE [CLIENTE](
[CPF] [CHAR] (11),
[NOME] [VARCHAR] (150),
[RUA] [VARCHAR] (150),
[COMPLEMENTO] [VARCHAR] (150),
[BAIRRO] [VARCHAR] (150),
[ESTADO] [CHAR] (2),
[CEP] [CHAR] (8),
[DATA DE NASCIMENTO] [DATE],
[IDADE] [SMALLINT],
[SEXO] [CHAR] (1),
[LIMITE DE CREDITO] [MONEY],
[VOLUME MINIMO] [FLOAT],
[PRIMEIRA COMPRA] [BIT]
);

CREATE TABLE [PRODUTOS](
[CODIGO DO PRODUTO] [VARCHAR] (20) NOT NULL PRIMARY KEY,
[NOME DO PRODUTO] [VARCHAR] (50),
[EMBALAGEM] [VARCHAR] (50),
[TAMANHO] [VARCHAR] (50),
[SABOR] [VARCHAR] (50),
[PRECO LISTA] [SMALLMONEY]
);

CREATE TABLE [TABELA DE VENDEDORES](
[MATRICULA] [VARCHAR] (5) NOT NULL PRIMARY KEY,
[NOME] [VARCHAR] (100),
[PERCENTUAL COMISSAO] [FLOAT]
);


--ALTERANDO UMA COLUNA DE UMA TABELA
ALTER TABLE [CLIENTE] ALTER COLUMN [CPF] [CHAR] (11) NOT NULL;

--ADICIONANDO UMA CHAVE PRIMARIA A UMA TABELA
ALTER TABLE [CLIENTE] ADD CONSTRAINT PK_CLIENTE PRIMARY KEY CLUSTERED (CPF);