

--FORMATANDO DADOS JÁ FORMATADOS
UPDATE PRODUTOS --TABELAS QUE VAMOS ALTERAR
SET [PRECO LISTA] = [PRECO LISTA] * 0.90 --LISTA QUE VAMOS ALTERAR
WHERE EMBALAGEM = 'LATA'; --RESTRIÇÃO PARA ALTERAÇÃO

--FORMATANDO DOIS DADOS SIMULTANEOS
UPDATE PRODUTOS 
SET EMBALAGEM = 'Garrafa', [PRECO LISTA] = 8.10
WHERE [CODIGO DO PRODUTO] = '1088126';

--EXCLUINDO DADOS JA CADASTRADOS
DELETE FROM PRODUTOS
WHERE [CODIGO DO PRODUTO] ='1004327';
