
--FILTRANDO CONSULTAS
SELECT NOME, ESTADO
FROM CLIENTE
WHERE [PRIMEIRA COMPRA] = 1;

SELECT *
FROM PRODUTOS
WHERE [PRECO LISTA] = 7;
/*

POSSO UTILIZAR OS OPERADORES
=	| IGUAL
>	| MAIOR QUE 
<	| MENOR QUE
>=	| MAIOR IGUAL
<=	| MENOR IGUAL
<>	| DIFERENTE

*/

--CONSULTA POR PALAVRA
SELECT *
FROM PRODUTOS
WHERE EMBALAGEM = 'LATA';

--CONSULTANDO DATAS
SELECT NOME, [DATA DE NASCIMENTO]
FROM CLIENTE
WHERE [DATA DE NASCIMENTO] > '1995-12-31';

--CONSULTANDO APENAS O ANO
SELECT NOME, [DATA DE NASCIMENTO]
FROM CLIENTE
WHERE YEAR([DATA DE NASCIMENTO]) > '1995';

--FILTROS COMPOSTOS 

--(TIPO OU)
SELECT NOME, BAIRRO
FROM CLIENTE
WHERE BAIRRO = 'Copacabana' OR BAIRRO = 'Tijuca'4

--(TIPO AND)
SELECT NOME, BAIRRO
FROM CLIENTE
WHERE ESTADO = 'SP' AND [PRIMEIRA COMPRA] = 1