--AGRUPANDO CONSULTAS
--TODOS ESSES CAMPOS ESTAO RELACIONADO AO GROUP BY, ENTÃO SEMPRE PRECISA EXISTIR UM AGRUPADOR (SUM/ MAX/ MIN/ AVG)
SELECT CIDADE, SUM(IDADE) FROM TABELA_DE_CLIENTES GROUP BY CIDADE; --SOMMANDO

SELECT CIDADE, MAX(IDADE) FROM TABELA_DE_CLIENTES GROUP BY CIDADE; --NUMERO MAXIMO

SELECT CIDADE, MIN(IDADE) FROM TABELA_DE_CLIENTES GROUP BY CIDADE; --NUMERO MINIMO

SELECT CIDADE, AVG(IDADE) FROM TABELA_DE_CLIENTES GROUP BY CIDADE; --MEDIA


--POSSO ORDENAR O MEU CONTADOR
SELECT CIDADE, COUNT(*) FROM TABELA_DE_CLIENTES GROUP BY CIDADE;

SELECT COUNT(CIDADE) FROM TABELA_DE_CLIENTES;