--CLASSIFICANDO OS CAMPO, UTILIZANDO A FUNCIONALIDADE (CASE/WHEN/THEN/ELSE)
--SEM UTILIZAR O CASE
SELECT 
	NOME_DO_PRODUTO, 
	PRECO_DE_LISTA 
FROM 
	TABELA_DE_PRODUTOS;

--UTILIZANDO O CASE
SELECT 
	NOME_DO_PRODUTO, 
	PRECO_DE_LISTA,
	(CASE 
		WHEN PRECO_DE_LISTA > 12 THEN 'CARO' --ADICIONANDO UMA CONDIÇÃO E RETORNANDO UM VALOR CASO ATENDA
		WHEN PRECO_DE_LISTA > 7 AND PRECO_DE_LISTA <= 12 THEN 'EM CONTA' --ADICIONANDO UMA CONDIÇÃO E RETORNANDO UM VALOR CASO ATENDA
		ELSE 'BARATO' --SE NENHUMA ACIMA ATENDER UTILIZAMOS ESSA
		END) AS CLASSIFICACAO --APELIDA PARA A NOVA COLUNA
FROM 
	TABELA_DE_PRODUTOS
ORDER BY CLASSIFICACAO; --CONSIGO ORDENAR PELO MEU CASE

--POSSO UTILIZAR O CASE E AINDA CONTAR
SELECT 
	(CASE 
		WHEN PRECO_DE_LISTA > 12 THEN 'CARO' 
		WHEN PRECO_DE_LISTA > 7 AND PRECO_DE_LISTA <= 12 THEN 'EM CONTA'
		ELSE 'BARATO'
		END) AS CLASSIFICACAO,
		COUNT(*) AS NUMERO_DE_PRODUTO --UTILIZANDO PARA CONTAR AS INFORMAÇÕES
FROM 
	TABELA_DE_PRODUTOS
GROUP BY(CASE 
		WHEN PRECO_DE_LISTA > 12 THEN 'CARO' 
		WHEN PRECO_DE_LISTA > 7 AND PRECO_DE_LISTA <= 12 THEN 'EM CONTA'
		ELSE 'BARATO'
		END); --PRECISO REPETIR SEM O APELIDO