
--APELIDOS PARA CONSULTAS
SELECT
	NOME AS [NOME DO CLIENTE] --APELIDO PARA COLUNA PRECISA DE 'AS' PARA FUNCIONAR
FROM 
	TABELA_DE_CLIENTES;

SELECT
	CLIENTES.NOME --UTILIZANDO O APELIDO, SEMPRE COM O "."
FROM 
	TABELA_DE_CLIENTES CLIENTES; --APELIDO PARA TABLEA PRECISA SER SUPRIMIDO
