
--TESTANDO FUNCOES

--TRANSFORMANDO TODOS CARACTERES EM MINUSCULO
SELECT LOWER('TESte dE converSão de TeXto');

--TRANSFORMANDO TODOS CARACTERES EM MAIIUSCULO
SELECT UPPER('TESte dE converSão de TeXto');

--CONCATENANDO VALORES
SELECT CONCAT('VINICIUS',000,'MENDONCA');

--CONSULTANDO UM DETERMINADO NÚMERO DE CARACTERES DE UMA FRASE, DETERMINANDO A QUANTIDADE DE RETORNO
SELECT RIGHT ('VINICIUS KIRSTEN MENDONCA', 8);--8 VAI SER A QUANTIDADE DE RETORNO (DIREITA PARA ESQUERDA)

SELECT LEFT ('VINICIUS KIRSTEN MENDONCA', 8);--8 VAI SER A QUANTIDADE DE RETORNO (ESQUERDA PARA DIREITA)

--CONSULTA QUE REPLICA O RETORNO A QUANTIDADE DE VEZES INFORMADA
SELECT REPLICATE('VINICIUS KIRSTEN MENDONCA', 8); --2 VAI SER A QUANTIDADE DE VEZES QUE A FRASE VAI SE REPETIR

--CONSULTA QUE LÊ APARTIR DE UMA POSIÇÃO E A QUANTIDADE DE CARACTERES APONTADAS
SELECT SUBSTRING('VINICIUS KIRSTEN MENDONCA', 2, 4) --2 VAI SER A POSIÇÃO / 4 VAI SER A QUANTIDADE DE CARACTERES

--CONSULTA REMOVENDO OS ESPAÇOS OU UM CARACTER ESPECIFICADO DA STRING
SELECT LTRIM('VINICIUS KIRSTEN MENDONCA', 'V'); --ELE RETIRA O 'V' DO COMEÇO DA FRASE