
SELECT 
	NOME,
	CIDADE
FROM
	TABELA_DE_CLIENTES
WHERE CIDADE = 'Rio de Janeiro';  --RESTRIÇÃO DA CONSULTA

SELECT * FROM TABELA_DE_CLIENTES WHERE DATA_DE_NASCIMENTO > '1995-11-14';
SELECT * FROM TABELA_DE_CLIENTES WHERE DATA_DE_NASCIMENTO < '1995-11-14';
SELECT * FROM TABELA_DE_CLIENTES WHERE DATA_DE_NASCIMENTO <= '1995-11-14';
SELECT * FROM TABELA_DE_CLIENTES WHERE DATA_DE_NASCIMENTO <> '1995-11-14';
SELECT * FROM TABELA_DE_CLIENTES WHERE DATA_DE_NASCIMENTO BETWEEN '1995-11-14' AND '2000-11-14'; --ENTRE

--OUTROS TIPOS DE RESTRIÇÕES
SELECT * FROM TABELA_DE_PRODUTOS WHERE SABOR = 'Manga' AND TAMANHO ='470 ml';
SELECT * FROM TABELA_DE_PRODUTOS WHERE SABOR = 'Manga' OR TAMANHO ='470 ml';
SELECT * FROM TABELA_DE_PRODUTOS WHERE NOT (SABOR = 'Manga' OR TAMANHO='470 ml');

SELECT * FROM TABELA_DE_PRODUTOS WHERE SABOR = 'Manga' OR SABOR = 'Laranja' OR SABOR = 'Melancia';
SELECT * FROM TABELA_DE_PRODUTOS WHERE SABOR in ('Manga', 'Laranja', 'Melancia'); --UTILLIZANDO ESSE TIPO DE EXPRESSÃO,
																				  -- É ALGO MAIS ELEGANTE QUE UM MONTE DE "OR"

SELECT * FROM TABELA_DE_PRODUTOS WHERE SABOR in ('Manga', 'Laranja', 'Melancia') AND EMBALAGEM = 'Garrafa';