--ANTES DO LIKE
SELECT * FROM TABELA_DE_PRODUTOS WHERE SABOR IN('Lima/Limao','Morango/Limao');

--CONSULTA BUSCANDO POR PALAVRAS/CARACTERES CHAVE
SELECT * FROM TABELA_DE_PRODUTOS WHERE SABOR LIKE '%Limao%'; --QUALQUER LOCAL COM A PALAVRA LIMAO

SELECT * FROM TABELA_DE_PRODUTOS WHERE SABOR LIKE '%Limao'; --TERMINA COM A PALAVRA LIMAO

SELECT * FROM TABELA_DE_PRODUTOS WHERE SABOR LIKE 'Limao%'; --COMEÇA COM A PALAVRA LIMAO

