--CONSULTA UTILIZANDO O INNET JOIN
--BUSCA OS VENDEDORES E CLIENTES QUE TEM O BAIRRO EM COMUM
SELECT DISTINCT 
	TV.NOME AS NOME_DO_VENDEDOR, 
	TV.BAIRRO AS BAIRRO_DO_VENDEDOR,
	TC.BAIRRO AS BAIRRO_DO_CLIENTE, 
	TC.NOME AS NOME_DO_CLIENTE 
FROM 
	TABELA_DE_CLIENTES TC 
	INNER JOIN TABELA_DE_VENDEDORES TV 
	ON TC.BAIRRO = TV.BAIRRO;

--CONSULTA UTILIZANDO O RIGHT JOIN
--BUSCA OS VENDEDORES QUE NAO TEM CLIENTE NO SEU BAIRRO
SELECT DISTINCT 
	TV.NOME AS NOME_DO_VENDEDOR, 
	TV.BAIRRO AS BAIRRO_DO_VENDEDOR,
	TC.BAIRRO AS BAIRRO_DO_CLIENTE, 
	TC.NOME AS NOME_DO_CLIENTE 
FROM TABELA_DE_CLIENTES TC 
	RIGHT JOIN TABELA_DE_VENDEDORES TV 
	ON TC.BAIRRO = TV.BAIRRO 
	WHERE TC.NOME IS NULL;

--CONSULTA UTILIZANDO O LEFT JOIN
---BUSCA OS CLIENTES QUE NAO TEM VENDEDOR NO SEU BAIRRO
SELECT DISTINCT 
	TV.NOME AS NOME_DO_VENDEDOR, 
	TV.BAIRRO AS BAIRRO_DO_VENDEDOR,
	TC.BAIRRO AS BAIRRO_DO_CLIENTE, 
	TC.NOME AS NOME_DO_CLIENTE 
FROM TABELA_DE_CLIENTES TC 
	LEFT JOIN TABELA_DE_VENDEDORES TV 
	ON TC.BAIRRO = TV.BAIRRO 
WHERE TV.NOME IS NULL;

--CCONSULTA UTILIZANDO O FULL JOIN
--BUSCA TODO OS DADOS DAS TABELAS DE VENDEDORES E CLIENTES
SELECT DISTINCT 
	TV.NOME AS NOME_DO_VENDEDOR, 
	TV.BAIRRO AS BAIRRO_DO_VENDEDOR,
	TC.BAIRRO AS BAIRRO_DO_CLIENTE, 
	TC.NOME AS NOME_DO_CLIENTE 
FROM TABELA_DE_CLIENTES TC 
	FULL JOIN TABELA_DE_VENDEDORES TV 
	ON TC.BAIRRO = TV.BAIRRO;
