--ADICIONA A DATA NA QUAL ESTAMOS SELECIONANDO, NO EXEMPLO ABAIXO ELE VAI ADICIONAR 30 DIAS A DATA
--LEMBRANDO QUE POSSO ADICIONAR QUALQUER CONTROLADOR, COMO O DE MÊS, ASSIM ELE VAI ADICIONAR PARTES DA INFORMACAO ANTERIOR
SELECT DATEADD(DAY, 30,'2022-01-01');

--RETRONA UM VALOR ESPECIFICO DE DATA DIA/MÊS/ANO/MINUTO/SEGUNDO
SELECT DATEPART(DAY,'2022-04-12');

--RETORNA O VALOR DA DIFERENÇA ENTRE DUAS DATAS, INDIFERENTE DA SUA DATEPART
--NO LUGAR DO DIA, POSSO UTILIZAR OUTRO TIPO DE PARTES DA SEMANA
SELECT DATEDIFF(DAY, '2022-01-01','2022-04-12');

--BUSCA A DATA ONDE O BANCO ESTÁ RODANDO
SELECT GETDATE();

--RETORNA A DATA QUE ESTA ENTRE PARENTES
SELECT DAY(GETDATE());

--RETORNA O MES QUE ESTA ENTRE PARENTES
SELECT MONTH(GETDATE());

--RETORNA O ANO QUE ESTA ENTRE PARENTES
SELECT YEAR(GETDATE());

--ELE TESTA PARA SABER SE AQUELA DATA E UMA EXPRESSAO 
--RETORNA OS VALORES "1" PARA VERDADEIRO E "0" PARA FALSO
SELECT ISDATE(GETDATE());