--ADICIONA A DATA NA QUAL ESTAMOS SELECIONANDO, NO EXEMPLO ABAIXO ELE VAI ADICIONAR 30 DIAS A DATA
--LEMBRANDO QUE POSSO ADICIONAR QUALQUER CONTROLADOR, COMO O DE MÊS
SELECT DATEADD(DAY, 30,'2022-01-01');

--RETRONA UM VALOR ESPECIFICO DE DATA DIA/MÊS/ANO/MINUTO/SEGUNDO
SELECT DATEPART(DAY,'2022-04-12');

--RETORNA O VALOR DA DIFERENÇA ENTRE DUAS DATAS, INDIFERENTE DA SUA DATEPART
--NO LUGAR DO DIA, POSSO UTILIZAR OUTRO TIPO DE PARTES DA SEMANA
SELECT DATEDIFF(DAY, '2022-01-01','2022-04-12');

--BUSCA A DATA ONDE O BANCO ESTÁ RODANDO
SELECT GETDATE();