/*PARA UTIILIZAR UM INNER JOIN NÃO É NECESSÁRIO UTILIZAR UMA PK,
APENAS TEMOS QUE TER EXATAMENTE OS MESMOS DADOS DE UMA TABELA*/

SELECT 
	VEND.MATRICULA,
	VEND.NOME,
	COUNT (*)
FROM
	NOTAS_FISCAIS AS NOTA
	INNER JOIN TABELA_DE_VENDEDORES AS VEND --JUNTANDO DUAS TABELAS COM OS DADOS /LEMBRANDO QUE ESTOU USANDO UM APELIDO PARA MINHA TABELA
	ON NOTA.MATRICULA = VEND.MATRICULA --ASSOCIANDO DUAS AMBAS AS TABELAS
GROUP BY
	VEND.MATRICULA,
	NOME;

--BOA PRATICA DE PROGRAMACAO É UTILIZAR SEMPRE A TABELA SUPERIOR NO FROM