--ORDENNDO A SAIDA DO RESULTADO
SELECT * FROM TABELA_DE_PRODUTOS
ORDER BY PRECO_DE_LISTA ASC; --"ASC" DO MENOR PARA O MAIOR / QUANDO NÃO COLOCAMOS NADA, FICA SUBENTENDIDO

SELECT * FROM TABELA_DE_PRODUTOS
ORDER BY PRECO_DE_LISTA DESC; --"DESC" DO MAIOR PAR O MENOR

--DESSA FORMA ELE VAI ORDERNAR PRIMEIRO POR EMBALAGEM, 
--POSTERIORMENTE VAI FILTRAR O NOME DOS PRODUTOS, DENTRO
--DOS FILTROS DE EMBALAGEM. SEMPRE RESPEITANDO A ORDEM DO COMANDO.
SELECT * FROM TABELA_DE_PRODUTOS
ORDER BY EMBALAGEM, NOME_DO_PRODUTO;

--VENDO OS 5 PRODUTOS MAIS CAROS
SELECT TOP 5 * FROM TABELA_DE_PRODUTOS ORDER BY PRECO_DE_LISTA DESC