--REFAZENDO UMA CONNSULTA COM HAVING, UTILIZANDO SUBCONSULTAS

--CONSULTA COM HAVING
SELECT 
	INF.CODIGO_DO_PRODUTO,
	TP.NOME_DO_PRODUTO,
	SUM(INF.QUANTIDADE) AS QUANTIDADE 
FROM 
	ITENS_NOTAS_FISCAIS  INF
INNER JOIN TABELA_DE_PRODUTOS TP 
ON INF.CODIGO_DO_PRODUTO = TP.CODIGO_DO_PRODUTO
GROUP BY 
	INF.CODIGO_DO_PRODUTO,
	TP.NOME_DO_PRODUTO HAVING SUM(INF.QUANTIDADE) > 394000 
ORDER BY SUM(INF.QUANTIDADE) DESC;

--CONSULTA SEM HAVING, UTILIZANDO SUBCONSULTA
SELECT 
	SC.CODIGO_DO_PRODUTO,
	SC.NOME_DO_PRODUTO,
	SC.QUANTIDADE_TOTAL
FROM
	(
	SELECT 
		INF.CODIGO_DO_PRODUTO,
		TP.NOME_DO_PRODUTO,
		SUM(INF.QUANTIDADE) AS QUANTIDADE_TOTAL 
	FROM 
		ITENS_NOTAS_FISCAIS  INF
	INNER JOIN TABELA_DE_PRODUTOS TP 
	ON INF.CODIGO_DO_PRODUTO = TP.CODIGO_DO_PRODUTO
GROUP BY 
	INF.CODIGO_DO_PRODUTO, TP.NOME_DO_PRODUTO) SC
WHERE 
	SC.QUANTIDADE_TOTAL > 394000 
ORDER BY SC.QUANTIDADE_TOTAL DESC;