--SELECIONANDO APENAS OS CLIENTES QUE TEM ALGUMA COOMPRA
SELECT DISTINCT 
	TC.CPF AS CPF_DO_CADASTRO,
	TC.NOME AS NOME_DO_CLIENTE,
	NF.CPF AS CPF_DA_NOTA
FROM 
	TABELA_DE_CLIENTES TC 
	INNER JOIN NOTAS_FISCAIS NF ON TC.CPF = NF.CPF;

--INSERINDO DADOS NA TABELA DE CLIENTES, PARA SIMULAR UM CLIENTE SEM COMPRA
INSERT INTO TABELA_DE_CLIENTES 
(CPF, NOME, ENDERECO_1, ENDERECO_2,
BAIRRO, CIDADE, ESTADO, CEP, DATA_DE_NASCIMENTO, IDADE, GENERO,
LIMITE_DE_CREDITO, VOLUME_DE_COMPRA, PRIMEIRA_COMPRA)
VALUES ('23412632331', 'Juliana Silva', 'Rua Tramandaí', ' ', 'Bangu', 'Rio de
Janeiro', 'RJ', '23400000', '1989-02-04', 33, 'F', '180000', '24500', 0);

--CONSULTANDO OS TODOS OS CLIENNTE E MOSTRANDO SE TEM ALGUMA COMPRA
SELECT DISTINCT 
	TC.CPF AS CPF_DO_CADASTRO,
	TC.NOME AS NOME_DO_CLIENTE,
	NF.CPF AS CPF_DA_NOTA
FROM 
	TABELA_DE_CLIENTES TC 
	LEFT JOIN NOTAS_FISCAIS NF ON TC.CPF = NF.CPF;

--SELECIONANDO OS CLIENTES QUE NAO REALIZARAM NENHUMA COMPRA
SELECT DISTINCT 
	TC.CPF AS CPF_DO_CADASTRO,
	TC.NOME AS NOME_DO_CLIENTE
FROM 
	TABELA_DE_CLIENTES TC 
	LEFT JOIN NOTAS_FISCAIS NF ON TC.CPF = NF.CPF --PEGA TUDO DA TABELA DA ESQUERDA
WHERE 
	NF.CPF IS NULL