
SELECT DISTINCT BAIRRO FROM TABELA_DE_CLIENTES;
--> 12 BAIRROS -> CLIENTE

SELECT DISTINCT BAIRRO FROM TABELA_DE_VENDEDORES;
--> 4 BAIRROS -> VENDEDORES


SELECT DISTINCT BAIRRO FROM TABELA_DE_CLIENTES
UNION
SELECT DISTINCT BAIRRO FROM TABELA_DE_VENDEDORES;
--13 TODOS DO CLIENTE E TODOS DO VENDEDOS SEM REPETIR

SELECT DISTINCT BAIRRO FROM TABELA_DE_CLIENTES
UNION ALL
SELECT DISTINCT BAIRRO FROM TABELA_DE_VENDEDORES;
--16 TODOS DO CLIENTE E TODOS DO VENDEDOS REPETINDO VALORES

--POSSO DIZER DE ONDE VEM A ORIGEM DESSES DADOS
SELECT DISTINCT BAIRRO, 'CLIENTE' FROM TABELA_DE_CLIENTES
UNION ALL
SELECT DISTINCT BAIRRO, 'VENDEDOR' FROM TABELA_DE_VENDEDORES;