
SELECT ESTADO, SUM(LIMITE_DE_CREDITO)
FROM TABELA_DE_CLIENTES
GROUP BY ESTADO;

--HAVING EXISTE POIS NAO PODEMOS COLOCAR SUM DENTRO DE UM WHERE,
--ASSIM SENDO NECESSARIO UTILIZAR ESSE TIPO DE FILTRO

--USANDO O HAVING
--NESSE FORMATO ELE VAI TRAZER TODOS OS ESTADOS QUE O LIMITE É MAIOR QUE 950000
SELECT ESTADO, SUM(LIMITE_DE_CREDITO)
FROM TABELA_DE_CLIENTES
GROUP BY ESTADO
HAVING SUM(LIMITE_DE_CREDITO) >= 950000;

SELECT
	EMBALAGEM, 
	MAX(PRECO_DE_LISTA), 
	MIN(PRECO_DE_LISTA)
FROM 
	TABELA_DE_PRODUTOS 
WHERE 
	PRECO_DE_LISTA >= 10 
GROUP BY 
	EMBALAGEM 
HAVING 
	MAX(PRECO_DE_LISTA) >=20;


SELECT CODIGO_DO_PRODUTO, SUM(QUANTIDADE) AS QUANTIDADE 
FROM ITENS_NOTAS_FISCAIS 
GROUP BY CODIGO_DO_PRODUTO 
HAVING SUM(QUANTIDADE) > 394000 
ORDER BY SUM(QUANTIDADE) DESC;